-- Phase 6E-B2 — real 40-fragrance catalogue (Standard 20 / Parfum 10 / VIP 10).
-- ADDITIVE. Safe to re-run: scents/translations use ON CONFLICT DO NOTHING so any
-- admin edit made via Admin -> Kokular after the first run is NEVER overwritten.
-- Existing 0002 seed scents (frisch-ocean, ...) are untouched — nothing is deleted
-- or deactivated. Codes are new/unique so there is no collision.

-- ---------------- STANDARD (20) ----------------
insert into scents (code, category, is_active, sort_order) values ('std-okyanus','frisch',true,100) on conflict (code) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'de','Okyanus','Frisch, maritim, klar' from scents where code='std-okyanus' on conflict (scent_id, locale) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'en','Ocean','Fresh, marine, clean' from scents where code='std-okyanus' on conflict (scent_id, locale) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'fr','Océan','Frais, marin, net' from scents where code='std-okyanus' on conflict (scent_id, locale) do nothing;
insert into scents (code, category, is_active, sort_order) values ('std-sakiz','suess',true,101) on conflict (code) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'de','Sakız','Süß, verspielt' from scents where code='std-sakiz' on conflict (scent_id, locale) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'en','Bubblegum','Sweet, playful' from scents where code='std-sakiz' on conflict (scent_id, locale) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'fr','Chewing-gum','Sucré, ludique' from scents where code='std-sakiz' on conflict (scent_id, locale) do nothing;
insert into scents (code, category, is_active, sort_order) values ('std-portakal','fruchtig',true,102) on conflict (code) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'de','Portakal','Spritzig, fruchtig' from scents where code='std-portakal' on conflict (scent_id, locale) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'en','Orange','Zesty, fruity' from scents where code='std-portakal' on conflict (scent_id, locale) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'fr','Orange','Pétillant, fruité' from scents where code='std-portakal' on conflict (scent_id, locale) do nothing;
insert into scents (code, category, is_active, sort_order) values ('std-cilek','fruchtig',true,103) on conflict (code) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'de','Çilek','Süß, fruchtig' from scents where code='std-cilek' on conflict (scent_id, locale) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'en','Strawberry','Sweet, fruity' from scents where code='std-cilek' on conflict (scent_id, locale) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'fr','Fraise','Sucré, fruité' from scents where code='std-cilek' on conflict (scent_id, locale) do nothing;
insert into scents (code, category, is_active, sort_order) values ('std-limon','fruchtig',true,104) on conflict (code) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'de','Limon','Frisch, säuerlich' from scents where code='std-limon' on conflict (scent_id, locale) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'en','Lemon','Fresh, tangy' from scents where code='std-limon' on conflict (scent_id, locale) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'fr','Citron','Frais, acidulé' from scents where code='std-limon' on conflict (scent_id, locale) do nothing;
insert into scents (code, category, is_active, sort_order) values ('std-bahar','frisch',true,105) on conflict (code) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'de','Bahar','Blumig, frisch' from scents where code='std-bahar' on conflict (scent_id, locale) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'en','Spring Blossom','Floral, fresh' from scents where code='std-bahar' on conflict (scent_id, locale) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'fr','Fleur de printemps','Floral, frais' from scents where code='std-bahar' on conflict (scent_id, locale) do nothing;
insert into scents (code, category, is_active, sort_order) values ('std-fresh','frisch',true,106) on conflict (code) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'de','Fresh','Klar, sauber' from scents where code='std-fresh' on conflict (scent_id, locale) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'en','Fresh','Clean, crisp' from scents where code='std-fresh' on conflict (scent_id, locale) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'fr','Fresh','Propre, frais' from scents where code='std-fresh' on conflict (scent_id, locale) do nothing;
insert into scents (code, category, is_active, sort_order) values ('std-mentol','frisch',true,107) on conflict (code) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'de','Mentol','Kühl, intensiv frisch' from scents where code='std-mentol' on conflict (scent_id, locale) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'en','Menthol','Cool, intensely fresh' from scents where code='std-mentol' on conflict (scent_id, locale) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'fr','Menthol','Frais, intense' from scents where code='std-mentol' on conflict (scent_id, locale) do nothing;
insert into scents (code, category, is_active, sort_order) values ('std-hanimeli','suess',true,108) on conflict (code) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'de','Hanımeli','Süß, blumig' from scents where code='std-hanimeli' on conflict (scent_id, locale) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'en','Honeysuckle','Sweet, floral' from scents where code='std-hanimeli' on conflict (scent_id, locale) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'fr','Chèvrefeuille','Sucré, floral' from scents where code='std-hanimeli' on conflict (scent_id, locale) do nothing;
insert into scents (code, category, is_active, sort_order) values ('std-mango','fruchtig',true,109) on conflict (code) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'de','Mango','Exotisch, fruchtig' from scents where code='std-mango' on conflict (scent_id, locale) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'en','Mango','Exotic, fruity' from scents where code='std-mango' on conflict (scent_id, locale) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'fr','Mangue','Exotique, fruité' from scents where code='std-mango' on conflict (scent_id, locale) do nothing;
insert into scents (code, category, is_active, sort_order) values ('std-elma','fruchtig',true,110) on conflict (code) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'de','Elma','Spritzig, fruchtig' from scents where code='std-elma' on conflict (scent_id, locale) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'en','Apple','Zesty, fruity' from scents where code='std-elma' on conflict (scent_id, locale) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'fr','Pomme','Pétillant, fruité' from scents where code='std-elma' on conflict (scent_id, locale) do nothing;
insert into scents (code, category, is_active, sort_order) values ('std-lavanta','elegant',true,111) on conflict (code) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'de','Lavanta','Beruhigend, blumig' from scents where code='std-lavanta' on conflict (scent_id, locale) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'en','Lavender','Calming, floral' from scents where code='std-lavanta' on conflict (scent_id, locale) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'fr','Lavande','Apaisant, floral' from scents where code='std-lavanta' on conflict (scent_id, locale) do nothing;
insert into scents (code, category, is_active, sort_order) values ('std-vanilya','suess',true,112) on conflict (code) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'de','Vanilya','Warm, süß, cremig' from scents where code='std-vanilya' on conflict (scent_id, locale) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'en','Vanilla','Warm, sweet, creamy' from scents where code='std-vanilya' on conflict (scent_id, locale) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'fr','Vanille','Chaud, sucré, crémeux' from scents where code='std-vanilya' on conflict (scent_id, locale) do nothing;
insert into scents (code, category, is_active, sort_order) values ('std-bogurtlen','fruchtig',true,113) on conflict (code) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'de','Blackberry / Böğürtlen','Saftig, süßlich' from scents where code='std-bogurtlen' on conflict (scent_id, locale) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'en','Blackberry','Juicy, sweetish' from scents where code='std-bogurtlen' on conflict (scent_id, locale) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'fr','Mûre','Juteux, sucré' from scents where code='std-bogurtlen' on conflict (scent_id, locale) do nothing;
insert into scents (code, category, is_active, sort_order) values ('std-latte','suess',true,114) on conflict (code) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'de','Latte / Sütlü Kahve','Cremig, röstig' from scents where code='std-latte' on conflict (scent_id, locale) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'en','Latte','Creamy, roasty' from scents where code='std-latte' on conflict (scent_id, locale) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'fr','Café au lait','Crémeux, torréfié' from scents where code='std-latte' on conflict (scent_id, locale) do nothing;
insert into scents (code, category, is_active, sort_order) values ('std-cam','frisch',true,115) on conflict (code) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'de','Çam','Waldig, frisch' from scents where code='std-cam' on conflict (scent_id, locale) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'en','Pine','Woodsy, fresh' from scents where code='std-cam' on conflict (scent_id, locale) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'fr','Pin','Boisé, frais' from scents where code='std-cam' on conflict (scent_id, locale) do nothing;
insert into scents (code, category, is_active, sort_order) values ('std-kavun','fruchtig',true,116) on conflict (code) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'de','Kavun','Süß, saftig' from scents where code='std-kavun' on conflict (scent_id, locale) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'en','Melon','Sweet, juicy' from scents where code='std-kavun' on conflict (scent_id, locale) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'fr','Melon','Sucré, juteux' from scents where code='std-kavun' on conflict (scent_id, locale) do nothing;
insert into scents (code, category, is_active, sort_order) values ('std-tropik','fruchtig',true,117) on conflict (code) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'de','Tropik Meyve','Exotisch, fruchtig' from scents where code='std-tropik' on conflict (scent_id, locale) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'en','Tropical Fruit','Exotic, fruity' from scents where code='std-tropik' on conflict (scent_id, locale) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'fr','Fruits tropicaux','Exotique, fruité' from scents where code='std-tropik' on conflict (scent_id, locale) do nothing;
insert into scents (code, category, is_active, sort_order) values ('std-burcu','elegant',true,118) on conflict (code) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'de','Burcu / Dove','Sanft, seifig-frisch' from scents where code='std-burcu' on conflict (scent_id, locale) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'en','Dove','Soft, soapy-fresh' from scents where code='std-burcu' on conflict (scent_id, locale) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'fr','Dove','Doux, frais-savonneux' from scents where code='std-burcu' on conflict (scent_id, locale) do nothing;
insert into scents (code, category, is_active, sort_order) values ('std-sakura','elegant',true,119) on conflict (code) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'de','Kiraz Çiçeği / Sakura','Zart, blumig' from scents where code='std-sakura' on conflict (scent_id, locale) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'en','Cherry Blossom','Delicate, floral' from scents where code='std-sakura' on conflict (scent_id, locale) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'fr','Fleur de cerisier','Délicat, floral' from scents where code='std-sakura' on conflict (scent_id, locale) do nothing;

-- ---------------- PARFÜM (10) ----------------
insert into scents (code, category, is_active, sort_order) values ('prf-bambu','elegant',true,200) on conflict (code) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'de','Bambu','Grün, holzig' from scents where code='prf-bambu' on conflict (scent_id, locale) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'en','Bamboo','Green, woody' from scents where code='prf-bambu' on conflict (scent_id, locale) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'fr','Bambou','Vert, boisé' from scents where code='prf-bambu' on conflict (scent_id, locale) do nothing;
insert into scents (code, category, is_active, sort_order) values ('prf-rainforest','frisch',true,201) on conflict (code) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'de','Rain Forest','Grün, frisch' from scents where code='prf-rainforest' on conflict (scent_id, locale) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'en','Rain Forest','Green, fresh' from scents where code='prf-rainforest' on conflict (scent_id, locale) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'fr','Forêt tropicale','Vert, frais' from scents where code='prf-rainforest' on conflict (scent_id, locale) do nothing;
insert into scents (code, category, is_active, sort_order) values ('prf-jeunefrance','elegant',true,202) on conflict (code) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'de','Jeune France','Elegant, puderig' from scents where code='prf-jeunefrance' on conflict (scent_id, locale) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'en','Jeune France','Elegant, powdery' from scents where code='prf-jeunefrance' on conflict (scent_id, locale) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'fr','Jeune France','Élégant, poudré' from scents where code='prf-jeunefrance' on conflict (scent_id, locale) do nothing;
insert into scents (code, category, is_active, sort_order) values ('prf-hollywood','elegant',true,203) on conflict (code) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'de','Hollywood','Glamourös, warm' from scents where code='prf-hollywood' on conflict (scent_id, locale) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'en','Hollywood','Glamorous, warm' from scents where code='prf-hollywood' on conflict (scent_id, locale) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'fr','Hollywood','Glamour, chaud' from scents where code='prf-hollywood' on conflict (scent_id, locale) do nothing;
insert into scents (code, category, is_active, sort_order) values ('prf-onemillion','intensiv',true,204) on conflict (code) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'de','One Million','Intensiv, würzig — Duftrichtung inspiriert' from scents where code='prf-onemillion' on conflict (scent_id, locale) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'en','One Million','Intense, spicy — scent profile inspired' from scents where code='prf-onemillion' on conflict (scent_id, locale) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'fr','One Million','Intense, épicé — profil olfactif inspiré' from scents where code='prf-onemillion' on conflict (scent_id, locale) do nothing;
insert into scents (code, category, is_active, sort_order) values ('prf-areonvanilla','suess',true,205) on conflict (code) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'de','Areon Vanilla','Süß, cremig' from scents where code='prf-areonvanilla' on conflict (scent_id, locale) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'en','Areon Vanilla','Sweet, creamy' from scents where code='prf-areonvanilla' on conflict (scent_id, locale) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'fr','Areon Vanilla','Sucré, crémeux' from scents where code='prf-areonvanilla' on conflict (scent_id, locale) do nothing;
insert into scents (code, category, is_active, sort_order) values ('prf-woody','elegant',true,206) on conflict (code) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'de','Woody','Holzig, warm' from scents where code='prf-woody' on conflict (scent_id, locale) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'en','Woody','Woody, warm' from scents where code='prf-woody' on conflict (scent_id, locale) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'fr','Boisé','Boisé, chaud' from scents where code='prf-woody' on conflict (scent_id, locale) do nothing;
insert into scents (code, category, is_active, sort_order) values ('prf-newcar','intensiv',true,207) on conflict (code) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'de','Little Trees New Car','Intensiv, technisch-frisch — Duftrichtung inspiriert' from scents where code='prf-newcar' on conflict (scent_id, locale) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'en','Little Trees New Car','Intense, technical-fresh — scent profile inspired' from scents where code='prf-newcar' on conflict (scent_id, locale) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'fr','Little Trees New Car','Intense, frais technique — profil olfactif inspiré' from scents where code='prf-newcar' on conflict (scent_id, locale) do nothing;
insert into scents (code, category, is_active, sort_order) values ('prf-americanvanilla','suess',true,208) on conflict (code) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'de','Little Trees American Vanilla','Süß, warm — Duftrichtung inspiriert' from scents where code='prf-americanvanilla' on conflict (scent_id, locale) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'en','Little Trees American Vanilla','Sweet, warm — scent profile inspired' from scents where code='prf-americanvanilla' on conflict (scent_id, locale) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'fr','Little Trees American Vanilla','Sucré, chaud — profil olfactif inspiré' from scents where code='prf-americanvanilla' on conflict (scent_id, locale) do nothing;
insert into scents (code, category, is_active, sort_order) values ('prf-blackice','intensiv',true,209) on conflict (code) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'de','Little Trees Black Ice','Kühl, intensiv — Duftrichtung inspiriert' from scents where code='prf-blackice' on conflict (scent_id, locale) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'en','Little Trees Black Ice','Cool, intense — scent profile inspired' from scents where code='prf-blackice' on conflict (scent_id, locale) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'fr','Little Trees Black Ice','Frais, intense — profil olfactif inspiré' from scents where code='prf-blackice' on conflict (scent_id, locale) do nothing;

-- ---------------- VIP (10) ----------------
insert into scents (code, category, is_active, sort_order) values ('vip-blackorchid','elegant',true,300) on conflict (code) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'de','Tom Ford Black Orchid','Edel, dunkel-blumig — Duftrichtung inspiriert' from scents where code='vip-blackorchid' on conflict (scent_id, locale) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'en','Tom Ford Black Orchid','Refined, dark floral — scent profile inspired' from scents where code='vip-blackorchid' on conflict (scent_id, locale) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'fr','Tom Ford Black Orchid','Raffiné, floral sombre — profil olfactif inspiré' from scents where code='vip-blackorchid' on conflict (scent_id, locale) do nothing;
insert into scents (code, category, is_active, sort_order) values ('vip-inviktus','intensiv',true,301) on conflict (code) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'de','Inviktus','Intensiv, frisch-würzig — Duftrichtung inspiriert' from scents where code='vip-inviktus' on conflict (scent_id, locale) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'en','Invictus','Intense, fresh-spicy — scent profile inspired' from scents where code='vip-inviktus' on conflict (scent_id, locale) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'fr','Invictus','Intense, frais-épicé — profil olfactif inspiré' from scents where code='vip-inviktus' on conflict (scent_id, locale) do nothing;
insert into scents (code, category, is_active, sort_order) values ('vip-boss','elegant',true,302) on conflict (code) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'de','Boss','Elegant, maskulin — Duftrichtung inspiriert' from scents where code='vip-boss' on conflict (scent_id, locale) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'en','Boss','Elegant, masculine — scent profile inspired' from scents where code='vip-boss' on conflict (scent_id, locale) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'fr','Boss','Élégant, masculin — profil olfactif inspiré' from scents where code='vip-boss' on conflict (scent_id, locale) do nothing;
insert into scents (code, category, is_active, sort_order) values ('vip-jampol','elegant',true,303) on conflict (code) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'de','Jampol','Edel, warm' from scents where code='vip-jampol' on conflict (scent_id, locale) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'en','Jampol','Refined, warm' from scents where code='vip-jampol' on conflict (scent_id, locale) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'fr','Jampol','Raffiné, chaud' from scents where code='vip-jampol' on conflict (scent_id, locale) do nothing;
insert into scents (code, category, is_active, sort_order) values ('vip-angel','suess',true,304) on conflict (code) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'de','Angel','Süß, gourmand — Duftrichtung inspiriert' from scents where code='vip-angel' on conflict (scent_id, locale) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'en','Angel','Sweet, gourmand — scent profile inspired' from scents where code='vip-angel' on conflict (scent_id, locale) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'fr','Angel','Sucré, gourmand — profil olfactif inspiré' from scents where code='vip-angel' on conflict (scent_id, locale) do nothing;
insert into scents (code, category, is_active, sort_order) values ('vip-zafira','elegant',true,305) on conflict (code) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'de','Zafira','Edel, blumig' from scents where code='vip-zafira' on conflict (scent_id, locale) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'en','Zafira','Refined, floral' from scents where code='vip-zafira' on conflict (scent_id, locale) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'fr','Zafira','Raffiné, floral' from scents where code='vip-zafira' on conflict (scent_id, locale) do nothing;
insert into scents (code, category, is_active, sort_order) values ('vip-isseymiyaki','frisch',true,306) on conflict (code) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'de','Issey Miyaki','Frisch, aquatisch — Duftrichtung inspiriert' from scents where code='vip-isseymiyaki' on conflict (scent_id, locale) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'en','Issey Miyake','Fresh, aquatic — scent profile inspired' from scents where code='vip-isseymiyaki' on conflict (scent_id, locale) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'fr','Issey Miyake','Frais, aquatique — profil olfactif inspiré' from scents where code='vip-isseymiyaki' on conflict (scent_id, locale) do nothing;
insert into scents (code, category, is_active, sort_order) values ('vip-burberryweekend','frisch',true,307) on conflict (code) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'de','Burberry Weekend','Frisch, unbeschwert — Duftrichtung inspiriert' from scents where code='vip-burberryweekend' on conflict (scent_id, locale) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'en','Burberry Weekend','Fresh, carefree — scent profile inspired' from scents where code='vip-burberryweekend' on conflict (scent_id, locale) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'fr','Burberry Weekend','Frais, léger — profil olfactif inspiré' from scents where code='vip-burberryweekend' on conflict (scent_id, locale) do nothing;
insert into scents (code, category, is_active, sort_order) values ('vip-sauvage','intensiv',true,308) on conflict (code) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'de','Sauvage / Dior','Intensiv, frisch-würzig — Duftrichtung inspiriert' from scents where code='vip-sauvage' on conflict (scent_id, locale) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'en','Sauvage','Intense, fresh-spicy — scent profile inspired' from scents where code='vip-sauvage' on conflict (scent_id, locale) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'fr','Sauvage','Intense, frais-épicé — profil olfactif inspiré' from scents where code='vip-sauvage' on conflict (scent_id, locale) do nothing;
insert into scents (code, category, is_active, sort_order) values ('vip-bleudechanel','elegant',true,309) on conflict (code) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'de','Bleu de Chanel','Elegant, holzig-frisch — Duftrichtung inspiriert' from scents where code='vip-bleudechanel' on conflict (scent_id, locale) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'en','Bleu de Chanel','Elegant, woody-fresh — scent profile inspired' from scents where code='vip-bleudechanel' on conflict (scent_id, locale) do nothing;
insert into scent_translations (scent_id, locale, name, description) select id,'fr','Bleu de Chanel','Élégant, boisé-frais — profil olfactif inspiré' from scents where code='vip-bleudechanel' on conflict (scent_id, locale) do nothing;

-- ---------------- link into products (additive; existing product_scents links from
-- 0002 are untouched) ----------------
-- Standard list -> BUGO-STD. Parfum list -> BUGO-PRM and BUGO-DLX (both mid/upper
-- tiers). VIP list -> BUGO-VIP only, matching that collection premium positioning.
insert into product_scents (product_id, scent_id) select p.id, s.id from products p, scents s where p.product_code='BUGO-STD' and s.code='std-okyanus' on conflict do nothing;
insert into product_scents (product_id, scent_id) select p.id, s.id from products p, scents s where p.product_code='BUGO-STD' and s.code='std-sakiz' on conflict do nothing;
insert into product_scents (product_id, scent_id) select p.id, s.id from products p, scents s where p.product_code='BUGO-STD' and s.code='std-portakal' on conflict do nothing;
insert into product_scents (product_id, scent_id) select p.id, s.id from products p, scents s where p.product_code='BUGO-STD' and s.code='std-cilek' on conflict do nothing;
insert into product_scents (product_id, scent_id) select p.id, s.id from products p, scents s where p.product_code='BUGO-STD' and s.code='std-limon' on conflict do nothing;
insert into product_scents (product_id, scent_id) select p.id, s.id from products p, scents s where p.product_code='BUGO-STD' and s.code='std-bahar' on conflict do nothing;
insert into product_scents (product_id, scent_id) select p.id, s.id from products p, scents s where p.product_code='BUGO-STD' and s.code='std-fresh' on conflict do nothing;
insert into product_scents (product_id, scent_id) select p.id, s.id from products p, scents s where p.product_code='BUGO-STD' and s.code='std-mentol' on conflict do nothing;
insert into product_scents (product_id, scent_id) select p.id, s.id from products p, scents s where p.product_code='BUGO-STD' and s.code='std-hanimeli' on conflict do nothing;
insert into product_scents (product_id, scent_id) select p.id, s.id from products p, scents s where p.product_code='BUGO-STD' and s.code='std-mango' on conflict do nothing;
insert into product_scents (product_id, scent_id) select p.id, s.id from products p, scents s where p.product_code='BUGO-STD' and s.code='std-elma' on conflict do nothing;
insert into product_scents (product_id, scent_id) select p.id, s.id from products p, scents s where p.product_code='BUGO-STD' and s.code='std-lavanta' on conflict do nothing;
insert into product_scents (product_id, scent_id) select p.id, s.id from products p, scents s where p.product_code='BUGO-STD' and s.code='std-vanilya' on conflict do nothing;
insert into product_scents (product_id, scent_id) select p.id, s.id from products p, scents s where p.product_code='BUGO-STD' and s.code='std-bogurtlen' on conflict do nothing;
insert into product_scents (product_id, scent_id) select p.id, s.id from products p, scents s where p.product_code='BUGO-STD' and s.code='std-latte' on conflict do nothing;
insert into product_scents (product_id, scent_id) select p.id, s.id from products p, scents s where p.product_code='BUGO-STD' and s.code='std-cam' on conflict do nothing;
insert into product_scents (product_id, scent_id) select p.id, s.id from products p, scents s where p.product_code='BUGO-STD' and s.code='std-kavun' on conflict do nothing;
insert into product_scents (product_id, scent_id) select p.id, s.id from products p, scents s where p.product_code='BUGO-STD' and s.code='std-tropik' on conflict do nothing;
insert into product_scents (product_id, scent_id) select p.id, s.id from products p, scents s where p.product_code='BUGO-STD' and s.code='std-burcu' on conflict do nothing;
insert into product_scents (product_id, scent_id) select p.id, s.id from products p, scents s where p.product_code='BUGO-STD' and s.code='std-sakura' on conflict do nothing;
insert into product_scents (product_id, scent_id) select p.id, s.id from products p, scents s where p.product_code='BUGO-PRM' and s.code='prf-bambu' on conflict do nothing;
insert into product_scents (product_id, scent_id) select p.id, s.id from products p, scents s where p.product_code='BUGO-PRM' and s.code='prf-rainforest' on conflict do nothing;
insert into product_scents (product_id, scent_id) select p.id, s.id from products p, scents s where p.product_code='BUGO-PRM' and s.code='prf-jeunefrance' on conflict do nothing;
insert into product_scents (product_id, scent_id) select p.id, s.id from products p, scents s where p.product_code='BUGO-PRM' and s.code='prf-hollywood' on conflict do nothing;
insert into product_scents (product_id, scent_id) select p.id, s.id from products p, scents s where p.product_code='BUGO-PRM' and s.code='prf-onemillion' on conflict do nothing;
insert into product_scents (product_id, scent_id) select p.id, s.id from products p, scents s where p.product_code='BUGO-PRM' and s.code='prf-areonvanilla' on conflict do nothing;
insert into product_scents (product_id, scent_id) select p.id, s.id from products p, scents s where p.product_code='BUGO-PRM' and s.code='prf-woody' on conflict do nothing;
insert into product_scents (product_id, scent_id) select p.id, s.id from products p, scents s where p.product_code='BUGO-PRM' and s.code='prf-newcar' on conflict do nothing;
insert into product_scents (product_id, scent_id) select p.id, s.id from products p, scents s where p.product_code='BUGO-PRM' and s.code='prf-americanvanilla' on conflict do nothing;
insert into product_scents (product_id, scent_id) select p.id, s.id from products p, scents s where p.product_code='BUGO-PRM' and s.code='prf-blackice' on conflict do nothing;
insert into product_scents (product_id, scent_id) select p.id, s.id from products p, scents s where p.product_code='BUGO-DLX' and s.code='prf-bambu' on conflict do nothing;
insert into product_scents (product_id, scent_id) select p.id, s.id from products p, scents s where p.product_code='BUGO-DLX' and s.code='prf-rainforest' on conflict do nothing;
insert into product_scents (product_id, scent_id) select p.id, s.id from products p, scents s where p.product_code='BUGO-DLX' and s.code='prf-jeunefrance' on conflict do nothing;
insert into product_scents (product_id, scent_id) select p.id, s.id from products p, scents s where p.product_code='BUGO-DLX' and s.code='prf-hollywood' on conflict do nothing;
insert into product_scents (product_id, scent_id) select p.id, s.id from products p, scents s where p.product_code='BUGO-DLX' and s.code='prf-onemillion' on conflict do nothing;
insert into product_scents (product_id, scent_id) select p.id, s.id from products p, scents s where p.product_code='BUGO-DLX' and s.code='prf-areonvanilla' on conflict do nothing;
insert into product_scents (product_id, scent_id) select p.id, s.id from products p, scents s where p.product_code='BUGO-DLX' and s.code='prf-woody' on conflict do nothing;
insert into product_scents (product_id, scent_id) select p.id, s.id from products p, scents s where p.product_code='BUGO-DLX' and s.code='prf-newcar' on conflict do nothing;
insert into product_scents (product_id, scent_id) select p.id, s.id from products p, scents s where p.product_code='BUGO-DLX' and s.code='prf-americanvanilla' on conflict do nothing;
insert into product_scents (product_id, scent_id) select p.id, s.id from products p, scents s where p.product_code='BUGO-DLX' and s.code='prf-blackice' on conflict do nothing;
insert into product_scents (product_id, scent_id) select p.id, s.id from products p, scents s where p.product_code='BUGO-VIP' and s.code='vip-blackorchid' on conflict do nothing;
insert into product_scents (product_id, scent_id) select p.id, s.id from products p, scents s where p.product_code='BUGO-VIP' and s.code='vip-inviktus' on conflict do nothing;
insert into product_scents (product_id, scent_id) select p.id, s.id from products p, scents s where p.product_code='BUGO-VIP' and s.code='vip-boss' on conflict do nothing;
insert into product_scents (product_id, scent_id) select p.id, s.id from products p, scents s where p.product_code='BUGO-VIP' and s.code='vip-jampol' on conflict do nothing;
insert into product_scents (product_id, scent_id) select p.id, s.id from products p, scents s where p.product_code='BUGO-VIP' and s.code='vip-angel' on conflict do nothing;
insert into product_scents (product_id, scent_id) select p.id, s.id from products p, scents s where p.product_code='BUGO-VIP' and s.code='vip-zafira' on conflict do nothing;
insert into product_scents (product_id, scent_id) select p.id, s.id from products p, scents s where p.product_code='BUGO-VIP' and s.code='vip-isseymiyaki' on conflict do nothing;
insert into product_scents (product_id, scent_id) select p.id, s.id from products p, scents s where p.product_code='BUGO-VIP' and s.code='vip-burberryweekend' on conflict do nothing;
insert into product_scents (product_id, scent_id) select p.id, s.id from products p, scents s where p.product_code='BUGO-VIP' and s.code='vip-sauvage' on conflict do nothing;
insert into product_scents (product_id, scent_id) select p.id, s.id from products p, scents s where p.product_code='BUGO-VIP' and s.code='vip-bleudechanel' on conflict do nothing;
